#!/usr/bin/env bash
# installs nginx with some configurations

sudo apt-get -y update
sudo apt-get -y install nginx

# the landing page
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html >/dev/null

# configuring the redirect_me
sudo sed -i '/server_name _;/a \ \ \ \ \ \ \ \ rewrite ^/redirect_me https://www.youtube.com/watch?v=QH3-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# starting the service
sudo service nginx start
