#!/usr/bin/env bash
# installs and configures HAProxy

#the installation
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8.\*

# configuration
sudo cp -a /etc/haproxy/haproxy.cfg{,.bak}
echo '
frontend for_client_hits
	bind *:80
	mode http
	default_backend all_servers

backend all_servers
	balance roundrobin
	mode http
	server web-01 34.232.68.194:80 check
	server web-02 54.173.210.20:80 check
' | sudo tee -a /etc/haproxy/haproxy.cfg

# allowing init
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# starting the service
sudo service haproxy restart
