#!/usr/bin/env bash
# an (init) script that manages the ``manage_my_process`` script
################################################

OUT="/var/run/my_process.pid"


start ()
{
	./manage_my_process &
	echo "$!" | sudo tee "$OUT" > /dev/null
}

stop ()
{
	pkill -f "./manage_my_process"
	sudo rm "$OUT"
}

case $1 in
	"start")
		start
		echo "manage_my_process started"
		;;
	"stop")
		stop
		echo "manage_my_process stopped"
		;;
	"restart")
		stop
		start
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
