#!/usr/bin/env bash
# prints the story of the /etc/passwd
#####################################

IFS=$'\n'

while read -r line
do
	username=$(echo "$line" | cut -d ':' -f1)
	password=$(echo "$line" | cut -d ':' -f2)
	uid=$(echo "$line" | cut -d ':' -f3)
	ugid=$(echo "$line" | cut -d ':' -f4)
	uidinfo=$(echo "$line" | cut -d ':' -f5)
	homedir=$(echo "$line" | cut -d ':' -f6)
	cs=$(echo "$line" | cut -d ':' -f7)
	echo "The user $username is part of the $ugid gang, lives in $homedir and rides $cs. $uid's place is protected by the passcode $password, more info about the user here: $uidinfo"
done < /etc/passwd