#!/usr/bin/env bash
# displays "Best School" 10 times.
# prints "bad luck" for number 4 which is bad luck in Chinese culture cuz it's
# pronunced "si" which is similar to the word death
# and 8 is good luck cuz it's pronounced "ba" which is similar to the word
# wealth
###################

s="Best School"
i=1

while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		 echo "good luck"
	else
		echo "$s"
	fi

	i=$(( i + 1 ))
done
