#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements.
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
###################################

cp /etc/hosts /etc/hosts.bak
cp /etc/hosts ~/hosts.new
sed -i "/127.0.0.1*./c\127.0.0.2 localhost" ~/hosts.new
if grep -q '.*facebook.com$' ~/hosts.new; then
	sed -i "/.*facebook.com$/c\8.8.8.8 facebook.com" ~/hosts.new
else
	printf "\n8.8.8.8 facebook.com" >> ~/hosts.new
fi
cp -f ~/hosts.new /etc/hosts
