#!/usr/bin/env bash
# makes the server uses the user nginx instead of the root
chmod 744 /etc/nginx/nginx.conf
sudo sed -i "s/#user www-data/user nginx" /etc/nginx/nginx.conf
sudo sed -i  -e "s/ 80 / 8080 /" -e "s/:80 /:8080 /" /etc/nginx/sites-available/default
sudo pkill apache2
sudo -u nginx service nginx restart
